//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SPS.Model
{
    public class Collaborator : User
    {
        public virtual decimal Salary { get; set; }

        public virtual Parking Parking { get; set; }
    }
}

