//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SPS.Model
{
    public interface IUser
    {
        string FirstName { get; set; }

        string LastName { get; set; }

        string Email { get; set; }

        string Telephone { get; set; }

        int Id { get; set; }

        string RG { get; set; }

        string CPF { get; set; }

        Address Address { get; set; }

        string Password { get; set; }

        Parking Parking { get; set; }
    }
}

