//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SPS.Model
{
    public class Parking
    {
        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual IList<Collaborator> Collaborators
        {
            get;
            set;
        }

        public virtual Address Address
        {
            get;
            set;
        }

        public virtual IList<ParkingSpace> Spaces
        {
            get;
            set;
        }
    }
}

