//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace SPS.Model
{
    public class Tag
    {
        [Key]
        public virtual string Id
        {
            get;
            set;
        }

        public virtual User User
        {
            get;
            set;
        }
    }
}

