//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SPS.Model
{
    public class Tag
    {
        public virtual int Id
        {
            get;
            set;
        }

        public virtual User User
        {
            get;
            set;
        }
    }
}

